export const PAGE_HREF: Record<string, string> = {
  "adm-dashboard": "/panel/dashboard",
  "kas-dashboard": "/panel/dashboard",
  "adm-dep": "/panel/deposit",
  "kas-dep": "/panel/deposit",
  "adm-export": "/panel/transactions",
  "kas-export": "/panel/transactions",
  "adm-siteler": "/panel/sites",
  "adm-uyeler": "/panel/users",
  "adm-kasiyerler": "/panel/cashiers",
  "adm-monitor": "/panel/monitor",
  "adm-personel": "/panel/personel",
  "kas-personel": "/panel/personel",
  "adm-reconciliation": "/panel/reconciliation",
  "adm-site-mutabakat": "/panel/site-reconciliation",
  "adm-giris": "/panel/login-logs",
  "adm-raporlar": "/panel/reports",
  "adm-supheliler": "/panel/suspicious",
  "adm-duyurular": "/panel/announcements",
  "kas-duyurular": "/panel/announcements",
  "adm-ayarlar": "/panel/settings",
  "kas-sifre": "/panel/settings",
  "adm-demo": "/panel/demo",
  "adm-pos": "/panel/pos",
};
